language: php

dist: trusty

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover=build/logs/coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover

notifications:
  email: never
