sudo: false

language: php

dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: never