sudo: false

language: php

dist: trusty

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: never