name: Tests

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '*.md'
      - '.github/**'

  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        experimental: [false]
        include:
          - php: 8.1
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        run: echo "${{ github.repository }} repository has been cloned."

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: none, curl
          coverage: xdebug

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

