name: Tests

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'example/**'

  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'example/**'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2]
        experimental: [false]
        include:
          - php: 8.1
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, curl
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: composer:v2

      - name: Composer Install
        run: composer install

      - name: analysis
        if: matrix.analysis
        run: vendor/bin/phpstan

      - name: Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml

